http:
  port: 8000
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  restaurant-search-api:
    host: localhost
    paths: '/search'
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  restaurant-search:
    url: 'http://localhost:8080'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
    
  restaurant-search-pipeline:
    apiEndpoints:
      - restaurant-search-api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    - key-auth:
      - proxy:
          - action:
              serviceEndpoint: restaurant-search 
              changeOrigin: true
